// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 scullymi
`default_nettype none   // game20k: a typo in a signal name must be an error, not a silent
                       // one-bit net.
//! @file menu_rom.v
//! @brief Menu description for the OSD: gzip-compressed XML, generated from galaga.xml.
//!
//! Generated by scripts/make_menu_hex.sh. The Companion fetches it via SPI target 0,
//! command READ_CFG.
//!
//! Why this is a module of its own: sysctrl_galaga.v mixes Till Harbaum's unlicensed lines
//! with ours and carries no SPDX tag. The generated menu content therefore lives in a file
//! that is entirely ours and GPL-3.0-only.
//!
//! The path below is relative to THIS file, not to the working directory of the synthesis.
//! Measured in the Gowin build: "galaga_xml.hex" fails, "../../galaga_xml.hex" finds
//! fpga/galaga_hdmi/galaga_xml.hex. Gowin does search further places (even
//! "../galaga_xml.hex" is found, via impl/), but only the source-file rule is explainable.
//! Cross-check: a wrong path produces exactly one warning EX3988 and otherwise NOTHING.
//! The build runs through, the menu ROM stays empty and the OSD is dead. Whoever moves
//! anything here checks the build log for EX3988.
module menu_rom (
  input             wire clk,
  input      wire [11:0] addr,
  output reg [7:0]  data
);

reg [7:0] galaga_xml[2048];
initial $readmemh("../../galaga_xml.hex", galaga_xml);

always @(posedge clk)
  data <= galaga_xml[addr];

endmodule

`default_nettype wire   // required: Gowin compiles ALL files as one unit, the directive
                        // would otherwise leak into the next file.
