// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 scullymi
`default_nettype none   // game20k: a typo in a signal name must be an error, not a silent
                       // one-bit net.
//! @file menu_rom.v
//! @brief Menu description for the OSD: gzip-compressed XML, generated from the game's menu.xml.
//!
//! Generated by scripts/make_menu_hex.sh. The Companion fetches it via SPI target 0,
//! command READ_CFG.
//!
//! Why this is a module of its own: sysctrl.v mixes Till Harbaum's lines with ours and is
//! GPL-3.0-or-later. The generated menu content therefore lives in a file that is entirely
//! ours and GPL-3.0-only.
//!
//! The path below is relative to the file the synthesis reads, not to its working
//! directory. Measured in the Gowin build: a bare file name fails, "../../<file>" from
//! src/mcu/ found the hex next to the project file. Gowin does search further places (even
//! "../<file>" is found, via impl/), but only the source-file rule is explainable.
//! This file lives in fpga/common, the menu is the game's: build.tcl therefore copies it to
//! gen/ of the game folder and compiles THAT copy, from where "../menu_xml.hex" is the
//! game's menu. The copy is the only way the same source serves every game.
//! Cross-check: a wrong path produces exactly one warning EX3988 and otherwise NOTHING.
//! The build runs through, the menu ROM stays empty and the OSD is dead. Whoever moves
//! anything here checks the build log for EX3988, fpga_report.py does so too.
module menu_rom (
  input             wire clk,
  input      wire [11:0] addr,
  output reg [7:0]  data
);

reg [7:0] menu_xml[2048];
initial $readmemh("../menu_xml.hex", menu_xml);

always @(posedge clk)
  data <= menu_xml[addr];

endmodule

`default_nettype wire   // required: Gowin compiles ALL files as one unit, the directive
                        // would otherwise leak into the next file.
